{
    "provider_name": "ElevenLabs",
    "api_base_url": "https://api.elevenlabs.io/v1",
    "tts": {
        "models": [
            {
                "name": "eleven_monolingual_v1",
                "display_name": "Eleven Monolingual v1",
                "description": "High-quality English-only model with natural speech",
                "languages": ["en"],
                "max_characters": 5000,
                "supported_formats": ["mp3"],
                "default_settings": {
                    "voice_id": "pNInz6obpgDQGcFmaJgB",
                    "stability": 0.5,
                    "similarity_boost": 0.5,
                    "style": 0.0,
                    "use_speaker_boost": true
                }
            },
            {
                "name": "eleven_multilingual_v1",
                "display_name": "Eleven Multilingual v1",
                "description": "Multilingual model supporting various languages",
                "languages": ["en", "es", "fr", "de", "it", "pt", "pl", "hi"],
                "max_characters": 5000,
                "supported_formats": ["mp3"],
                "default_settings": {
                    "voice_id": "pNInz6obpgDQGcFmaJgB",
                    "stability": 0.5,
                    "similarity_boost": 0.5,
                    "style": 0.0,
                    "use_speaker_boost": true
                }
            },
            {
                "name": "eleven_multilingual_v2",
                "display_name": "Eleven Multilingual v2",
                "description": "Enhanced multilingual model with improved quality",
                "languages": ["en", "es", "fr", "de", "it", "pt", "pl", "hi", "ja", "ko", "zh"],
                "max_characters": 5000,
                "supported_formats": ["mp3"],
                "default_settings": {
                    "voice_id": "pNInz6obpgDQGcFmaJgB",
                    "stability": 0.5,
                    "similarity_boost": 0.5,
                    "style": 0.0,
                    "use_speaker_boost": true
                }
            },
            {
                "name": "eleven_turbo_v2",
                "display_name": "Eleven Turbo v2",
                "description": "Fast, low-latency model optimized for speed",
                "languages": ["en"],
                "max_characters": 5000,
                "supported_formats": ["mp3"],
                "default_settings": {
                    "voice_id": "pNInz6obpgDQGcFmaJgB",
                    "stability": 0.5,
                    "similarity_boost": 0.5,
                    "style": 0.0,
                    "use_speaker_boost": true
                }
            }
        ],
        "voices": [
            {
                "voice_id": "pNInz6obpgDQGcFmaJgB",
                "name": "Adam",
                "gender": "male",
                "accent": "american",
                "description": "Deep, authoritative voice"
            },
            {
                "voice_id": "EXAVITQu4vr4xnSDxMaL",
                "name": "Bella",
                "gender": "female",
                "accent": "american",
                "description": "Soft, warm female voice"
            },
            {
                "voice_id": "ErXwobaYiN019PkySvjV",
                "name": "Antoni",
                "gender": "male",
                "accent": "american",
                "description": "Well-rounded, versatile voice"
            },
            {
                "voice_id": "VR6AewLTigWG4xSOukaG",
                "name": "Arnold",
                "gender": "male",
                "accent": "american",
                "description": "Crisp, clear narration voice"
            },
            {
                "voice_id": "rrnqDWOzpnfpJXyiEeHA",
                "name": "Domi",
                "gender": "female",
                "accent": "american",
                "description": "Strong, confident female voice"
            },
            {
                "voice_id": "AZnzlk1XvdvUeBnXmlld",
                "name": "Elli",
                "gender": "female",
                "accent": "american",
                "description": "Emotional, expressive voice"
            },
            {
                "voice_id": "MF3mGyEYCl7XYWbV9V6O",
                "name": "Elli",
                "gender": "female",
                "accent": "american",
                "description": "Young, energetic voice"
            },
            {
                "voice_id": "TxGEqnHWrfWFTfGW9XjX",
                "name": "Josh",
                "gender": "male",
                "accent": "american",
                "description": "Deep, calm voice"
            },
            {
                "voice_id": "CYw3kZ02Hs0563khs1Fj",
                "name": "Rachel",
                "gender": "female",
                "accent": "american",
                "description": "Calm, pleasant voice"
            },
            {
                "voice_id": "29vD33N1CtxCmqQRPOHJ",
                "name": "Drew",
                "gender": "male",
                "accent": "american",
                "description": "Well-balanced, natural voice"
            }
        ]
    },
    "stt": {
        "models": [
            {
                "name": "eleven_speech_to_text_v1",
                "display_name": "ElevenLabs Speech-to-Text v1",
                "description": "High-quality speech recognition model",
                "languages": ["en"],
                "supported_formats": ["wav", "mp3", "mp4", "m4a", "flac", "ogg"],
                "max_file_size": "25MB",
                "default_settings": {
                    "language": "en"
                }
            }
        ],
        "note": "ElevenLabs Speech-to-Text service"
    },
    "rate_limits": {
        "requests_per_minute": 120,
        "characters_per_month": 10000,
        "concurrent_requests": 2
    },
    "authentication": {
        "type": "api_key",
        "header_name": "xi-api-key",
        "env_var": "ELEVENLABS_API_KEY"
    },
    "error_handling": {
        "retry_attempts": 3,
        "retry_delay": 1.0,
        "timeout_seconds": 60,
        "common_errors": [
            {
                "code": 401,
                "message": "Invalid API key",
                "retry": false
            },
            {
                "code": 429,
                "message": "Rate limit exceeded",
                "retry": true,
                "wait_time": 60
            },
            {
                "code": 413,
                "message": "Audio file too large",
                "retry": false
            }
        ]
    },
    "health_check": {
        "endpoint": "/user",
        "timeout_seconds": 10,
        "expected_status_codes": [200]
    }
}